### ISSUE TITLE
Automatic wrapper generation

### ISSUE THREAD

**Issue by BotellaA** [master-atul/blog-addons-example#2]
Do you have an idea to generate the ClassExample directly from the ActualClass? I mean, all the information is already inside the class declaration. It must have a way to generate de ClassExample from the ActualClass.

What do you think about this?

**Comment by a7ul** [comment]
Hi @BotellaA  
It should be possible.

I think this library does it https://github.com/charto/nbind
This is exactly the same library used by facebook in their yoga project.

The only caveat is that it uses NAN instead of NAPI.

Maybe you can take inspiration from it.
I haven't personally ventured into it for NAPI yet.

**Comment by BotellaA** [comment]
Yes, I am currently using nbind but I would like to move away from NAN to NAPI. However, I do not really understand how nbind works...

**Comment by a7ul** [comment]
I read the source code a while ago. It mostly uses templates I think. Although I think that would be best answered by its creator. 

But I think our issue also can be solved by using class templates. But I haven't tried it though.

**Comment by BotellaA** [comment]
Ok, I will look again at the code.
